### ISSUE TITLE
Add support for Apple Silicon simulators

### ISSUE THREAD

**Issue by empowerCassie** [argyle-systems/argyle-link-ios#6]
Currently, the framework only ships with "x86_64" simulator support. Could you please add "arm64" simulator support so we can test on simulators for computers running the M1 chipset?

**Comment by Varnius** [comment]
Hi @empowerCassie - this is on our roadmap. I assume your current workaround for this is setting EXCLUDED_ARCHS to arm64, right?

**Comment by Varnius** [comment]
Fixed with [4.1.0](https://github.com/argyle-systems/argyle-link-ios/releases/tag/4.1.0)

**Comment by empowerCassie** [comment]
Thanks @Varnius
